# https://kit.svelte.dev/docs/adapter-static#github-pages
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: make install

      - name: build
        env:
          BASE_URL: "/westlake-timeline"
          VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}
        run: |
          make build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

      - name: commit
        run: |
          timestamp=$(date -u)
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Updated: ${timestamp}" || exit 0
          git push

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
